In [28]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB


In [5]:
df.Category.describe()

count     5572
unique       2
top        ham
freq      4825
Name: Category, dtype: object

In [6]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [8]:
df['spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [12]:
X_train.shape

(4457,)

In [13]:
X_test.shape

(1115,)

In [14]:
type(X_train)

pandas.core.series.Series

In [15]:
X_train[:4]

1569    Today is ACCEPT DAY..U Accept me as? Brother S...
3863                     Customer place, i wil cal u sir.
2153    Hi kindly give us back our documents which we ...
1094    Well the weather in cali's great. But its comp...
Name: Message, dtype: object

In [16]:
type(y_test)

pandas.core.series.Series

In [17]:
y_test[:4]

2481    1
1700    0
4294    0
3695    0
Name: spam, dtype: int64

In [18]:
type(X_train.values)

numpy.ndarray

Create bag of words representation using CountVectorizer

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7772 sparse matrix of type '<class 'numpy.int64'>'
	with 59619 stored elements in Compressed Sparse Row format>

In [21]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
X_train_cv.shape

(4457, 7772)

In [24]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'èn', 'ú1'], dtype=object)

In [25]:
v.vocabulary_

{'today': 6970,
 'is': 3763,
 'accept': 783,
 'day': 2193,
 'me': 4415,
 'as': 1097,
 'brother': 1532,
 'sister': 6206,
 'lover': 4241,
 'dear1': 2207,
 'best1': 1334,
 'clos1': 1854,
 'lvblefrnd': 4279,
 'jstfrnd': 3877,
 'cutefrnd': 2145,
 'lifpartnr': 4116,
 'belovd': 1324,
 'swtheart': 6694,
 'bstfrnd': 1544,
 'no': 4795,
 'rply': 5848,
 'means': 4421,
 'enemy': 2603,
 'customer': 2140,
 'place': 5228,
 'wil': 7543,
 'cal': 1608,
 'sir': 6203,
 'hi': 3432,
 'kindly': 3956,
 'give': 3156,
 'us': 7246,
 'back': 1201,
 'our': 5013,
 'documents': 2394,
 'which': 7519,
 'we': 7448,
 'submitted': 6586,
 'for': 2952,
 'loan': 4179,
 'from': 3032,
 'stapati': 6467,
 'well': 7484,
 'the': 6848,
 'weather': 7456,
 'in': 3657,
 'cali': 1611,
 'great': 3245,
 'but': 1582,
 'its': 3782,
 'complexities': 1944,
 'are': 1064,
 'you': 7736,
 'need': 4728,
 'car': 1656,
 'to': 6964,
 'move': 4608,
 'freely': 3001,
 'taxes': 6751,
 'outrageous': 5023,
 'all': 925,
 'sad': 5885,
 'part': 5089,
 'missi

In [26]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
np.where(X_train_np[0]!=0)

(array([ 783, 1097, 1324, 1334, 1532, 1544, 1854, 2145, 2193, 2207, 2603,
        3763, 3877, 4116, 4241, 4279, 4415, 4421, 4795, 5848, 6206, 6694,
        6970]),)

In [30]:
X_train[:4]

1569    Today is ACCEPT DAY..U Accept me as? Brother S...
3863                     Customer place, i wil cal u sir.
2153    Hi kindly give us back our documents which we ...
1094    Well the weather in cali's great. But its comp...
Name: Message, dtype: object

In [31]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [33]:
X_test_cv = v.transform(X_test)

In [35]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       979
           1       0.97      0.89      0.93       136

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [36]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

Train the model using sklearn pipeline and reduce number of lines of code

In [37]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [38]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [39]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       979
           1       0.97      0.89      0.93       136

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

